export default [
  'Acetate',
  'Adrenaline',
  'Albumen/Albumin',
  'Allantoin',
  'AlluraRed',
  'Alphahydroxyacids',
  'Aminoacids',
  'Amylase',
  'Artificial',
  'AsparticAcid',
  'Beeswax',
  'Biotin',
  'BrilliantBlueFCF',
  'CalciumCarbonate',
  'CalciumHydroxide',
  'CalciumLactate',
  'CalciumPhosphate',
  'CalciumStearate',
  'Calciumstearoyl-2-lactylate',
  'CaneSugar',
  'Caramel',
  'Carbamide',
  'CarbonBlack',
  'Catalase',
  'Cetylalcohol',
  'Cetylpalmitate',
  'Chalk',
  'Charcoal',
  'Chondroitin',
  'Chymosin',
  'Civet',
  'Colors/Dyes',
  'Corticosteroid/Cortisone',
  'Cysteine,L-Form',
  'Cystine',
  'D&CColors',
  'DiCalciumPhosphate',
  'Dihydroxyacetone',
  'Disodiuminosinate',
  'Enzymes',
  'Ergocalciferol',
  'Fattyacids',
  'FD&CColors',
  'FD&CBlue1',
  'FD&CRed40',
  'FD&CYellow5',
  'FD&CYellow6',
  'Feathers',
  'Felt',
  'FerrousLactate',
  'Folate',
  'Gluconodelta-lactone',
  'Gluconolactone',
  'Glucose',
  'Glucosamine',
  'Glycerin',
  'glycerol',
  'Glycine',
  'Inositol',
  'Insulin',
  'L-cysteine',
  'L-cysteinehydrochloride',
  'Lacticacid',
  'Lactoflavin',
  'Lecithin',
  'Lipase',
  'Lutein',
  'Magnesiumstearate',
  'Monoazo',
  'MonocalciumPhosphate',
  'Mono-Diglycerides',
  'Musk',
  'Natural',
  'Naturalflavor',
  'Niacin',
  'NicotinicAcid',
  'NutritionalYeast',
  'Oestrogen',
  'Oleicacid',
  'Oleicalcohol',
  'Oleth-2through50',
  'OrangeYellowS',
  'Palmitate',
  'Palmiticacid',
  'Panthenol',
  'Dexpanthenol',
  'VitaminBComplexFactor',
  'Parchment',
  'PEG',
  'Polyglycerolpolyricinoleate',
  'Polysorbate60',
  'Polysorbate80',
  'Polyoxyethylene(8)stearate',
  'Polyoxyethylene(40)stearate',
  'PotassiumLactate',
  'Progesterone',
  'Propyleneglycol',
  'QuinolineYellow',
  'Rennet',
  'Rennin',
  'Red40',
  'Riboflavin',
  'Riboflavin-5-Phosphate',
  'SodiumLactate',
  'Sodiumstearoyl-2-lactylate',
  'Sorbitanmonostearate',
  'Sorbitanmonooleate',
  'Sorbitantristearate',
  'SorbitanTrioleate',
  'Sourdoughstarter',
  'Sponge',
  'Squalene/squalane',
  'Stearate',
  'Stearicacid',
  'Stearin(e)',
  'Stearylalcohol',
  'Stearyltartrate(Stearylpalmityltartrate)',
  'Sucroglycerides',
  'Sucralose',
  'Sucrose',
  'Suede',
  'Suet',
  'Sugar',
  'SunsetYellowFCF',
  'Tartrazine(',
  'Testosterone',
  'TricalciumPhosphate',
  'Urea',
  'VegetableCarbon',
  'Vellum',
  'Velvet',
  'VitaminA(retinol)',
  'VitaminB1(Thiamine,Thiamin)',
  'VitaminB2(Riboflavin,Lactoflavin)',
  'VitaminB3(Niacin,NicotinicAcid)',
  'VitaminB7',
  'VitaminB9(FolicAcid,Folate)',
  'VitaminBFactor',
  'VitaminD2(Ergocalciferol)',
  'VitaminD3(Cholecalciferol)',
  'VitaminH',
  'WaxedPaper',
  'Xanthangum(cornsugargum)',
  'Yellow5',
  'Yellow6',
  'E101',
  'E101a',
  'E102',
  'E104',
  'E110',
  'E129',
  'E133',
  'E150a',
  'E150b',
  'E150c',
  'E150d',
  'E153',
  'E170',
  'E270',
  'E322',
  'E325',
  'E326',
  'E327',
  'E341',
  'E375',
  'E415',
  'E422',
  'E430',
  'E431',
  'E432',
  'E433',
  'E434',
  'E435',
  'E436',
  'E470',
  'E470',
  'E471',
  'E472',
  'E472',
  'E472',
  'E472',
  'E472',
  'E472',
  'E473',
  'E474',
  'E475',
  'E476',
  'E477',
  'E478',
  'E479',
  'E481',
  'E482',
  'E483',
  'E491',
  'E492',
  'E494',
  'E526',
  'E570',
  'E572',
  'E585',
  'E631',
  'E640',
  'E901',
  'E910',
  'E920',
  'Vitamin D',
  'fish-liver oil',
  'DEPANTHENOL',
  'DIGLYCERIDES',
  'Monoglycerides',
  'Glycerides',
  'DUODENUM SUBSTANCES',
  'ELASTIN',
  'INSULIN',
  'Myristyl',
  'L-LACTIC ACID',
  'LACTIC ACID',
  'LECITHIN',
  'LIPOIDS',
  'Magnesium Lanolate',
  'Magnesium Tallowate',
  'METHIONINE',
  'NUCLEIC ACID',
  'OCTYL DODECANOL',
  'OLEIC ACID',
  'Oleth-2',
  'Oleth-3',
  'Oleth-20',
  'Oleyl Alcohol',
  'Oleamine',
  'Oleyl Betaine',
  'Oleostearine',
  'PALMITATE',
  'Palmitic Acid',
  'PEG-28 Glyceryl Tallowate',
  'PEG-8 Hydrogenated Fish Glycerides',
  'PEG-5 through -70Hydrogenated Lanolin',
  'PEG-13 Hydrogenated Tallow Amide',
  'PEG-5 to -20 Lanolate',
  'PEG-5 through -100 Lanolin',
  'PEG-75 Lanolin Oil and Wax',
  'PEG-2 Milk Solids',
  'PEG-6, -8, -20 Sorbitan Beeswax',
  'PEG-40, -75, or -80 Sorbitan Lanolate',
  'PEG-3, -10, or -15 Tallow Aminopropylamine',
  'PEG-15 Tallow Polyamine',
  'PEG-20 Tallowate',
  'POLYSORBATES',
  'PROGESTERONE',
  'Stearate',
  'RENNET',
  'RENNIN',
  'SQUALANE: Squalene',
  'STEARATE',
  'STEARIN',
  'STEARIC ACID: See Quaterniun 27.',
  'STEARYL ALCOHOL',
  'STEROID: Sterol',
  'STEROL',
  'Taurine',
  'VITAMIN A',
  'VITAMIN B COMPLEX FACTOR',
  'VITAMIN B FACTOR',
  'VITAMIN B12',
  'VITAMIN D',
  'VITAMIN H.'
];
